/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Polygon;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;

/**
 *
 * @author a1743953
 */
public class Interface extends javax.swing.JFrame {

    private Arduino conn = new Arduino();
    private Calcula calcula = new Calcula();
    private Integer anguloA;
    private Integer anguloB;
    private Integer anguloC;
    private Rectangle braco1;
    private Rectangle braco2;

    /**
     * Creates new form Interface
     */
    public Interface() {
        this.anguloB = 0;
        this.anguloC = 0;
        initComponents();
        lblValorJuntaA.setText(anguloA.toString());
        lblValorJuntaB.setText(anguloB.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblValorJuntaA = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblValorGarra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblValorJuntaB = new javax.swing.JLabel();
        pnlDesenho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Junta A");

        lblValorJuntaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorJuntaA.setText("0");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Garra");

        lblValorGarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorGarra.setText("0");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Junta B");

        lblValorJuntaB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorJuntaB.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorJuntaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(lblValorGarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorJuntaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorJuntaA)
                    .addComponent(lblValorGarra)
                    .addComponent(lblValorJuntaB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDesenho.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlDesenhoLayout = new javax.swing.GroupLayout(pnlDesenho);
        pnlDesenho.setLayout(pnlDesenhoLayout);
        pnlDesenhoLayout.setHorizontalGroup(
            pnlDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDesenhoLayout.setVerticalGroup(
            pnlDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        Double x1 = calcula.calcularX(Math.toRadians(anguloA), Math.toRadians(anguloB));
        Double y1 = calcula.calcularY(Math.toRadians(anguloA), Math.toRadians(anguloB));
        Double angulo2 = (calcula.calcularAnguloX(calcula.calcularX(Math.toRadians(anguloA), Math.toRadians(anguloB)), calcula.calcularY(Math.toRadians(anguloA), Math.toRadians(anguloB))));
        Double angulo1 = (calcula.calcularAnguloY(calcula.calcularX(Math.toRadians(anguloA), Math.toRadians(anguloB)), calcula.calcularY(Math.toRadians(anguloA), Math.toRadians(anguloB))));
        System.out.println("Ponto x :" + calcula.calcularX(Math.toRadians(anguloA), Math.toRadians(anguloB)));
        System.out.println("Ponto y :" + calcula.calcularY(Math.toRadians(anguloA), Math.toRadians(anguloB)));
        
        System.out.println("Angulo A : " + calcula.calcularAnguloX(calcula.calcularX(Math.toRadians(anguloA), Math.toRadians(anguloB)), calcula.calcularY(Math.toRadians(anguloA), Math.toRadians(anguloB))));
        System.out.println("Angulo B : " + calcula.calcularAnguloY(calcula.calcularX(Math.toRadians(anguloA), Math.toRadians(anguloB)), calcula.calcularY(Math.toRadians(anguloA), Math.toRadians(anguloB))));
        if (evt.getKeyCode() == 37) {
            if (anguloA >= 10) {
                anguloA -= 10;
                lblValorJuntaA.setText(anguloA.toString());
            }
        }
        if (evt.getKeyCode() == 39) {
            if (anguloA <= 80) {
                anguloA += 10;
                lblValorJuntaA.setText(anguloA.toString());
            }
        }
        if (evt.getKeyCode() == 38) {
            if (anguloB <= 80) {
                anguloB += 10;
                lblValorJuntaB.setText(anguloB.toString());
            }
        }
        if (evt.getKeyCode() == 40) {
            if (anguloB >= 10) {
                anguloB -= 10;
                lblValorJuntaB.setText(anguloB.toString());
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_2) {
            if (anguloC <= 23) {
                anguloC += 2;
                lblValorGarra.setText(anguloC.toString());
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_1) {
            if (anguloC >= 2) {
                anguloC -= 2;
                lblValorGarra.setText(anguloC.toString());
            }
        }
        
        desenha( x1 , y1 , angulo1, angulo2);
        
       //conn.comunicacaoArduino(anguloA,'x');
       //conn.comunicacaoArduino(anguloB,'y');
       //conn.comunicacaoArduino(anguloC,'z');
    }//GEN-LAST:event_formKeyReleased

    
    public void desenha(double x1 ,  double y1 , double angulo1 , double angulo2) {
       
        System.out.println("Cos " + (int) (Math.cos(Math.toRadians(angulo2)) * 13));
        System.out.println("Sin " + (int) (Math.sin(Math.toRadians(angulo2)) * 13));
        
        Graphics grafico = pnlDesenho.getGraphics();
        grafico.setColor(Color.BLUE);
        grafico.drawLine(100 , 100, 200 +  ((int) ( Math.cos(Math.toRadians(angulo1)) * 13)) , 100 - ((int) Math.sin(Math.toRadians(angulo1)) * 13));
        grafico.drawLine(100 + (int) Math.cos(Math.toRadians(angulo1)) * 13 , 100 - (int) Math.sin(Math.toRadians(angulo1)) * 13 , ((int) x1 + 100) , ((int) -y1 + 100));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblValorGarra;
    private javax.swing.JLabel lblValorJuntaA;
    private javax.swing.JLabel lblValorJuntaB;
    private javax.swing.JPanel pnlDesenho;
    // End of variables declaration//GEN-END:variables
}
