/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.event.KeyEvent;

/**
 *
 * @author a1743953
 */
public class Interface extends javax.swing.JFrame {

    private Arduino conn = new Arduino();
    private Calcula calcula = new Calcula();
    private Integer anguloA;
    private Integer anguloB;
    private Integer anguloC;

    /**
     * Creates new form Interface
     */
    public Interface() {
        this.anguloA = 0;
        this.anguloB = 0;
        this.anguloC = 0;
        initComponents();
        lblValorJuntaA.setText(anguloA.toString());
        lblValorJuntaB.setText(anguloB.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblValorJuntaA = new javax.swing.JLabel();
        lblValorJuntaB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblValorGarra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("Junta A");

        jLabel2.setText("Junta B");

        lblValorJuntaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorJuntaA.setText("0");

        lblValorJuntaB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorJuntaB.setText("0");

        jLabel3.setText("Garra");

        lblValorGarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorGarra.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValorJuntaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValorGarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorJuntaB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorGarra))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorJuntaA)
                            .addComponent(lblValorJuntaB))))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        System.out.println("Ponto x :" + calcula.calcularX(Math.toRadians(anguloA), Math.toRadians(anguloB)));
        System.out.println("Ponto y :" + calcula.calcularY(Math.toRadians(anguloA), Math.toRadians(anguloB)));
        //System.out.println("anguloA :" + calcula.calcularAnguloX(calcula.calcularX(Math.toRadians(anguloA), Math.toRadians(anguloB)), calcula.calcularY(Math.toRadians(anguloA), Math.toRadians(anguloB))));
        //System.out.println("anguloA :" + calcula.calcularAnguloY(calcula.calcularX(Math.toRadians(anguloA), Math.toRadians(anguloB)), calcula.calcularY(Math.toRadians(anguloA), Math.toRadians(anguloB))));
        System.out.println(calcula.calcularAnguloX(23, 0));
        System.out.println(calcula.calcularAnguloY(23, 0));
        if (evt.getKeyCode() == 37) {
            if (anguloA >= 10) {
                anguloA -= 10;
                lblValorJuntaA.setText(anguloA.toString());
            }
        }
        if (evt.getKeyCode() == 39) {
            if (anguloA <= 80) {
                anguloA += 10;
                lblValorJuntaA.setText(anguloA.toString());
            }
        }
        if (evt.getKeyCode() == 38) {
            if (anguloB <= 80) {
                anguloB += 10;
                lblValorJuntaB.setText(anguloB.toString());
            }
        }
        if (evt.getKeyCode() == 40) {
            if (anguloB >= 10) {
                anguloB -= 10;
                lblValorJuntaB.setText(anguloB.toString());
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_2) {
            if (anguloC <= 23) {
                anguloC += 2;
                lblValorGarra.setText(anguloC.toString());
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_1) {
            if (anguloC >= 2) {
                anguloC -= 2;
                lblValorGarra.setText(anguloC.toString());
            }
        }
        
       // conn.comunicacaoArduino(anguloA,'x');
       // conn.comunicacaoArduino(anguloB,'y');
       // conn.comunicacaoArduino(anguloC,'z');
    }//GEN-LAST:event_formKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblValorGarra;
    private javax.swing.JLabel lblValorJuntaA;
    private javax.swing.JLabel lblValorJuntaB;
    // End of variables declaration//GEN-END:variables
}
